import { JetBrains_Mono } from "@next/font/google";
import localFont from "@next/font/local";
import { DarkModeScript } from "@strawberry-graphql/styleguide";
import {
  Header,
  GlowEffect,
  Hero,
  Spacer,
  FeaturesSection,
  SponsorsSection,
  Footer,
} from "@strawberry-graphql/styleguide";
import "@strawberry-graphql/styleguide/dist/index.css";
import clsx from "clsx";

import { fetchLatestRelease } from "~/lib/api";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const ranade = localFont({
  src: [
    {
      path: "../fonts/Ranade-Variable.ttf",
      style: "normal",
    },
    {
      path: "../fonts/Ranade-VariableItalic.ttf",
      style: "italic",
    },
  ],
  variable: "--font-ranade",
  // style: ["normal", "italic"],
});

const satoshi = localFont({
  src: [
    {
      path: "../fonts/Satoshi-Variable.ttf",
      style: "normal",
    },
    {
      path: "../fonts/Satoshi-VariableItalic.ttf",
      style: "italic",
    },
  ],
  variable: "--font-satoshi",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
});

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const version = await fetchLatestRelease();

  return (
    <html lang="en">
      {/*
        <head /> will contain the components returned by the nearest parent
        head.tsx. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
      */}
      <head>
        <DarkModeScript />
      </head>
      <body
        className={clsx(
          ranade.variable,
          satoshi.variable,
          jetbrainsMono.variable,
          "font-sans"
        )}
      >
        <Header
          version={{
            href: "/",
            name: version,
          }}
        />

        {children}

        <Footer />
      </body>
    </html>
  );
}
